on:
  push:
    branches:
      - main

jobs:
  analyze-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x

      - name: Set Project Path
        run: echo "PROJECT_PATH=$(pwd)" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore Roslyn/Roslyn.csproj

      - name: Build and Run Roslyn Analysis
        run: dotnet run --project Roslyn/Roslyn.csproj

      - name: Commit and Push Report
        run: |
          git config user.name "yrjeong97"
          git config user.email "yrjeong@ati2000.co.kr"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add non_pascal_names.txt
            git commit -m "Add non-PascalCase report"
            git push origin main
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          PROJECT_PATH: ${{ env.PROJECT_PATH }}