name: Roslyn Analysis Workflow

on:
  push:
    branches:
      - main

jobs:
  analyze-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x

      - name: Set Project Path
        run: echo "PROJECT_PATH=$(pwd)" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore Roslyn/Roslyn.csproj

      - name: Build and Run Roslyn Analysis
        run: dotnet run --project Roslyn/Roslyn.csproj

      - name: Run Roslyn Analysis Script
        run: dotnet run --project Roslyn/Roslyn.csproj
        env:
          PROJECT_PATH: ${{ env.PROJECT_PATH }}

      - name: Create Report File with Timestamp
        run: |
          timestamp=$(date +"%Y%m%d%H%M%S")
          reportFilePath="non_pascal_names_${timestamp}.txt"
          echo "Creating report file: $reportFilePath"
          echo "Your report content here" > $reportFilePath
        id: create_report

      - name: Commit and Push Report
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add ${{ steps.create_report.outputs.reportFilePath }}
          git diff-index --quiet HEAD || git commit -m "Add non-PascalCase names report"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
