name: Roslyn Analysis Workflow

on:
  push:
    branches:
      - '*release*'

jobs:
  analyze-code:
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout repository
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x

      - name: Set Project Path
        run: echo "PROJECT_PATH=$(pwd)" >> $GITHUB_ENV

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v38

      - name: Set changed .cs files as environment variable
        run: |
          cs_files=""
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ "$file" == *.cs ]]; then
              cs_files="$cs_files;$file"
              echo "$file added to cs_files"
            fi
          done
          echo "$cs_files"
          echo "CHANGED_FILES=$cs_files" >> $GITHUB_ENV
          
      - name: Extract Keywords from Description
        run: |
          DESCRIPTION=$(git log -1 --pretty=%B)
          KEYWORDS=$(echo "$DESCRIPTION" | grep -o '#[^ ]*' | sed 's/#//g' | tr -d ' ' | tr '\n' ';')    
          echo "KEYWORDS=$KEYWORDS" >> $GITHUB_ENV
      - name: Restore dependencies
        run: dotnet restore Roslyn/Roslyn.csproj

      - name: Analyze and Create Report File
        run: |
          timestamp=$(date +"%Y%m%d%H%M")
          reportFilePath="coding_rule_violation_${timestamp}.txt"
          echo "Creating report file: $reportFilePath"
          echo "" > $reportFilePath
          echo "::set-output name=reportFilePath::$reportFilePath"
          echo "REPORT_FILE_PATH=$reportFilePath" >> $GITHUB_ENV
        id: create_report

      - name: Build and Run Roslyn Analysis
        run: |
          REPORT_FILE_PATH="${REPORT_FILE_PATH// /}"
          dotnet run --project Roslyn/Roslyn.csproj >> $REPORT_FILE_PATH
        env:
          KEYWORDS: ${{env.KEYWORDS}}
          CHANGED_FILES: ${{env.CHANGED_FILES}}
          PROJECT_PATH: ${{ env.PROJECT_PATH }}
          REPORT_FILE_PATH: ${{ env.REPORT_FILE_PATH }}

      - name: Add Changes to Staging
        run: |
          git add $REPORT_FILE_PATH
        id: add_changes

      - name: Commit and Push Report
        run: |
          git config user.name "yrjeong97"
          git config user.email "yrjeong@ati2000.co.kr"
          branch="${{ github.ref }}"
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "Add coding standard report"
            git diff-index --quiet HEAD -- ':!roslyn_report.txt' || git commit -m "Add non-PascalCase names report"
            git push origin "$branch"
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          PROJECT_PATH: ${{ env.PROJECT_PATH }}
