name: Roslyn Analysis Workflow

on:
  push:
    branches:
      - main

jobs:
  analyze-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x

      - name: Set Project Path
        run: echo "PROJECT_PATH=$(pwd)" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore Roslyn/Roslyn.csproj

      - name: Build and Run Roslyn Analysis
        run: dotnet run --project Roslyn/Roslyn.csproj

      - name: Run Roslyn Analysis Script
        run: dotnet run --project Roslyn/Roslyn.csproj
        env:
          PROJECT_PATH: ${{ env.PROJECT_PATH }}
